on:
  push:
    branches: [ "main" ]

jobs:
  combo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pkgbuild
        uses: BeyondAUR-Aux/beyondaur-pkgbuild-action@v2.0.0
